CREATE TABLE doctor (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    cpf VARCHAR(14) NOT NULL,
    crm VARCHAR(255) UNIQUE NOT NULL,
    specialty VARCHAR(255) NOT NULL
);